"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import { createDocumentAction, createPdfDocumentAction, logoutAction } from "@/app/dashboard/actions";
import { DocumentLibrary } from "@/components/DocumentLibrary";
import { TwoFactorSettings } from "@/components/TwoFactorSettings";
import type { SignatureDocument } from "@/lib/documents";
import type { SecurityActivity } from "@/lib/auth";

type Tab = "overview" | "create" | "pdf" | "documents" | "security";
type LibraryFilter = "active" | "waiting" | "completed" | "archived" | "all";
type Query = { created?: string; duplicated?: string; pdfCreated?: string; pdfError?: string; error?: string; sent?: string; mailError?: string };
const tabs: Array<[Tab, string]> = [["overview", "סקירה"], ["create", "יצירת מסמך"], ["pdf", "העלאת PDF"], ["documents", "ספריית מסמכים"], ["security", "אבטחת חשבון"]];
const RichDocumentEditor = dynamic(() => import("@/components/RichDocumentEditor").then((module) => module.RichDocumentEditor), { ssr: false, loading: () => <LoadingPanel label="טוען את הכתבן…" /> });
const MultiSignaturePdfBuilder = dynamic(() => import("@/components/MultiSignaturePdfBuilder").then((module) => module.MultiSignaturePdfBuilder), { ssr: false, loading: () => <LoadingPanel label="טוען את כלי ה־PDF…" /> });

function tabFromHash(): Tab { const value = window.location.hash.replace("#", "") as Tab; return tabs.some(([tab]) => tab === value) ? value : "overview"; }

export function DashboardWorkspace({ documents, siteUrl, twoFactorEnabled, recoveryCodesRemaining, securityActivity, stats, query }: { documents: SignatureDocument[]; siteUrl: string; twoFactorEnabled: boolean; recoveryCodesRemaining: number; securityActivity: SecurityActivity[]; stats: { active: number; waiting: number; completed: number; signers: number }; query: Query }) {
  const [activeTab, setActiveTab] = useState<Tab>("overview");
  const [libraryFilter, setLibraryFilter] = useState<LibraryFilter>("active");
  useEffect(() => { const sync = () => setActiveTab(tabFromHash()); sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  function open(tab: Tab, filter?: LibraryFilter) { if (filter) setLibraryFilter(filter); setActiveTab(tab); window.history.replaceState(null, "", `#${tab}`); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <div className="container-site">
    <header className="relative overflow-hidden rounded-[var(--radius-xl)] border border-electric/15 bg-[linear-gradient(135deg,rgba(14,165,233,.14),rgba(15,23,42,.82)_52%,rgba(139,92,246,.09))] p-5 shadow-2xl sm:p-7">
      <div className="relative flex flex-wrap items-start justify-between gap-5"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full border border-green-300/20 bg-green-300/10 px-3 py-1 text-xs font-bold text-green-100">● מערכת פעילה</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-silver">אזור ניהול מאובטח</span></div><h1 className="text-3xl font-black text-white sm:text-4xl">מרכז ניהול חוזים</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-silver-muted">יצירה, חתימה, מעקב ואבטחה במקום אחד.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => open("create")} className="btn btn-primary text-sm">+ מסמך חדש</button><form action={logoutAction}><button className="btn btn-secondary text-sm">יציאה</button></form></div></div>
      <div className="relative mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4"><StatButton label="מסמכים פעילים" value={stats.active} tone="sky" onClick={() => open("documents", "active")} /><StatButton label="ממתינים לחתימה" value={stats.waiting} tone="amber" onClick={() => open("documents", "waiting")} /><StatButton label="הושלמו" value={stats.completed} tone="green" onClick={() => open("documents", "completed")} /><StatButton label="חותמים מנוהלים" value={stats.signers} tone="violet" onClick={() => open("documents", "all")} /></div>
    </header>
    {(query.created || query.pdfCreated || query.duplicated) ? <div className="mt-4 rounded-2xl border border-green-400/25 bg-green-400/10 p-4 text-green-100" role="status">הפעולה הושלמה. המסמך זמין בספרייה.</div> : null}
    {query.sent ? <div className="mt-4 rounded-2xl border border-green-400/25 bg-green-400/10 p-4 text-green-100" role="status">המסמך נשלח בהצלחה.</div> : null}
    {query.mailError ? <div className="mt-4 rounded-2xl border border-red-400/25 bg-red-400/10 p-4 text-red-100" role="alert">לא ניתן לשלוח את המייל כרגע.</div> : null}
    <nav className="sticky top-20 z-40 mt-4 flex gap-1 overflow-x-auto rounded-2xl border border-white/10 bg-[#07111f]/95 p-2 shadow-xl backdrop-blur-xl" aria-label="ניווט באזור הניהול">{tabs.map(([tab, label]) => <button key={tab} type="button" onClick={() => open(tab)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold transition ${activeTab === tab ? "bg-electric text-slate-950" : "text-silver hover:bg-white/5 hover:text-white"}`} aria-current={activeTab === tab ? "page" : undefined}>{label}</button>)}<Link href="/work-agreement" className="mr-auto whitespace-nowrap rounded-xl px-4 py-2.5 text-sm text-electric-bright hover:bg-electric/10">מסמכים ציבוריים</Link></nav>
    <div className="mt-6">
      {activeTab === "overview" ? <Overview stats={stats} open={open} /> : null}
      {activeTab === "create" ? <section aria-labelledby="create-title"><SectionTitle kicker="מסמך חדש" title="יצירת מסמך בעורך החכם" id="create-title" /><form action={createDocumentAction} className="glass space-y-5 rounded-[var(--radius-xl)] p-4 sm:p-7">{query.error ? <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{query.error === "open-fields" ? "נמצאו במסמך פרטים שלא מולאו. השלימו אותם או אשרו במפורש את יצירת הקישור." : "יש להשלים שם לקוח, כותרת ותוכן."}</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Field name="recipientName" label="שם הלקוח / החותם" placeholder="ישראל ישראלי" required /><Field name="recipientEmail" label="אימייל" placeholder="name@example.com" type="email" /></div><RichDocumentEditor /><div className="sticky bottom-3 z-30 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-electric/20 bg-[#07111f]/95 p-3 shadow-2xl backdrop-blur-xl"><span className="text-xs text-silver-muted">לפני היצירה תתבצע בדיקה של שדות חסרים.</span><button className="btn btn-primary min-w-64" type="submit">שמירה ויצירת קישור לחתימה</button></div></form></section> : null}
      {activeTab === "pdf" ? <section aria-labelledby="pdf-title"><SectionTitle kicker="מסמך קיים" title="העלאת PDF והוספת חתימות" id="pdf-title" /><div className="glass rounded-[var(--radius-xl)] p-4 sm:p-7">{query.pdfError ? <p className="mb-5 rounded-xl bg-red-400/10 p-4 text-sm text-red-200">לא הצלחנו להכין את ה־PDF. בדקו את הקובץ ואת מיקומי החתימות.</p> : null}<form action={createPdfDocumentAction}><MultiSignaturePdfBuilder /></form></div></section> : null}
      {activeTab === "documents" ? <DocumentLibrary key={libraryFilter} documents={documents} siteUrl={siteUrl} requestedFilter={libraryFilter} /> : null}
      {activeTab === "security" ? <section aria-labelledby="security-title"><SectionTitle kicker="גישה מוגנת" title="אבטחת החשבון" id="security-title" /><TwoFactorSettings initialEnabled={twoFactorEnabled} initialRecoveryCodesRemaining={recoveryCodesRemaining} /><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.05] p-5"><h3 className="font-bold text-white">הכניסה מנוהלת באמצעות Google</h3><p className="mt-2 text-sm leading-relaxed text-silver-muted">אין צורך בסיסמה נוספת במערכת. שינוי הסיסמה מתבצע בחשבון Google, והאימות הדו־שלבי כאן מוסיף שכבת הגנה נוספת.</p><a href="https://myaccount.google.com/security" target="_blank" rel="noreferrer" className="btn btn-secondary mt-4 text-sm">פתיחת אבטחת חשבון Google</a></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="font-bold text-white">פעילות כניסה אחרונה</h3><div className="mt-3 space-y-2">{securityActivity.length ? securityActivity.map((item) => <div key={item.id} className="rounded-xl border border-white/8 bg-black/10 p-3"><p className="text-sm font-bold text-silver">כניסה מאושרת · {new Intl.DateTimeFormat("he-IL", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.createdAt))}</p><p className="mt-1 truncate text-xs text-silver-muted" title={item.device}>{item.device}</p><p className="mt-1 text-[11px] text-silver-muted">מזהה רשת: {item.ipHint}</p></div>) : <p className="text-sm text-silver-muted">פעילות חדשה תופיע כאן לאחר הכניסה הבאה.</p>}</div></div></div></section> : null}
    </div>
  </div>;
}

function Overview({ stats, open }: { stats: { waiting: number; completed: number }; open: (tab: Tab, filter?: LibraryFilter) => void }) { return <section className="grid gap-4 lg:grid-cols-3"><QuickAction title="יצירת מסמך" text="בחירת תבנית, מילוי אוטומטי ועריכה כמו ב־Word." action="התחלת מסמך" onClick={() => open("create")} /><QuickAction title="חתימה על PDF" text="העלאת PDF, הוספת חותמים וסימון מקומות חתימה." action="העלאת PDF" onClick={() => open("pdf")} /><QuickAction title="מעקב מסמכים" text={`${stats.waiting} ממתינים ו־${stats.completed} הושלמו.`} action="פתיחת הספרייה" onClick={() => open("documents")} /></section>; }
function QuickAction({ title, text, action, onClick }: { title: string; text: string; action: string; onClick: () => void }) { return <article className="glass rounded-2xl p-6"><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-2 min-h-12 text-sm leading-relaxed text-silver-muted">{text}</p><button type="button" onClick={onClick} className="btn btn-secondary mt-5 w-full text-sm">{action}</button></article>; }
function LoadingPanel({ label }: { label: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center text-sm text-silver-muted" role="status">{label}</div>; }
function SectionTitle({ kicker, title, id }: { kicker: string; title: string; id: string }) { return <div className="mb-5"><p className="text-sm font-bold text-electric-bright">{kicker}</p><h2 id={id} className="mt-1 text-2xl font-bold text-white sm:text-3xl">{title}</h2></div>; }
function Field({ name, label, placeholder, required, type = "text" }: { name: string; label: string; placeholder: string; required?: boolean; type?: string }) { return <label className="block text-sm font-semibold text-silver">{label}<input name={name} required={required} type={type} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-white placeholder:text-silver-muted" /></label>; }
function StatButton({ label, value, tone, onClick }: { label: string; value: number; tone: "sky" | "amber" | "green" | "violet"; onClick: () => void }) { const colors = { sky: "border-sky-300/15 bg-sky-300/[0.07] text-sky-100", amber: "border-amber-300/15 bg-amber-300/[0.07] text-amber-100", green: "border-green-300/15 bg-green-300/[0.07] text-green-100", violet: "border-violet-300/15 bg-violet-300/[0.07] text-violet-100" }; return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-right transition hover:-translate-y-0.5 hover:border-electric/30 ${colors[tone]}`}><span className="block text-2xl font-black sm:text-3xl">{value.toLocaleString("he-IL")}</span><span className="mt-1 block text-xs font-bold opacity-75">{label}</span></button>; }
