"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import { createDocumentAction, createPdfDocumentAction, logoutAction } from "@/app/dashboard/actions";
import { DocumentLibrary } from "@/components/DocumentLibrary";
import { TwoFactorSettings } from "@/components/TwoFactorSettings";
import type { SecurityActivity } from "@/lib/auth";
import type { Customer } from "@/lib/customers";
import type { SignatureDocument } from "@/lib/documents";

type Tab = "overview" | "create" | "pdf" | "documents" | "customers" | "security";
type LibraryFilter = "active" | "waiting" | "completed" | "archived" | "all";
type Query = { created?: string; duplicated?: string; pdfCreated?: string; pdfError?: string; error?: string; sent?: string; mailError?: string };
type HtmlSigner = { id: string; label: string; name: string; identityNumber: string; email: string; phone: string };

const tabs: Array<[Tab, string]> = [["overview", "סקירה"], ["create", "יצירת מסמך"], ["pdf", "העלאת PDF"], ["documents", "ספריית מסמכים"], ["customers", "לקוחות"], ["security", "אבטחת חשבון"]];
const RichDocumentEditor = dynamic(() => import("@/components/RichDocumentEditor").then((module) => module.RichDocumentEditor), { ssr: false, loading: () => <LoadingPanel label="טוען את הכתבן…" /> });
const MultiSignaturePdfBuilder = dynamic(() => import("@/components/MultiSignaturePdfBuilder").then((module) => module.MultiSignaturePdfBuilder), { ssr: false, loading: () => <LoadingPanel label="טוען את כלי ה־PDF…" /> });

function blankSigner(index: number): HtmlSigner {
  return { id: `html-signer-${Date.now()}-${index}`, label: index === 0 ? "הלקוח" : `חותם ${index + 1}`, name: "", identityNumber: "", email: "", phone: "" };
}
function tabFromHash(): Tab { const value = window.location.hash.replace("#", "") as Tab; return tabs.some(([tab]) => tab === value) ? value : "overview"; }

export function DashboardWorkspace({ documents, customers, siteUrl, twoFactorEnabled, recoveryCodesRemaining, securityActivity, stats, query }: {
  documents: SignatureDocument[]; customers: Customer[]; siteUrl: string; twoFactorEnabled: boolean; recoveryCodesRemaining: number;
  securityActivity: SecurityActivity[]; stats: { active: number; waiting: number; completed: number; signers: number }; query: Query;
}) {
  const [activeTab, setActiveTab] = useState<Tab>("overview");
  const [libraryFilter, setLibraryFilter] = useState<LibraryFilter>("active");
  const [signers, setSigners] = useState<HtmlSigner[]>(() => [blankSigner(0)]);
  useEffect(() => { const sync = () => setActiveTab(tabFromHash()); sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  function open(tab: Tab, filter?: LibraryFilter) { if (filter) setLibraryFilter(filter); setActiveTab(tab); window.history.replaceState(null, "", `#${tab}`); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function updateSigner(index: number, values: Partial<HtmlSigner>) { setSigners((current) => current.map((signer, signerIndex) => signerIndex === index ? { ...signer, ...values } : signer)); }
  function selectCustomer(index: number, customerId: string) { const customer = customers.find((item) => item.id === customerId); if (customer) updateSigner(index, { name: customer.fullName, identityNumber: customer.identityNumber, email: customer.email, phone: customer.phone }); }
  function createForCustomer(customer: Customer) { setSigners([{ ...blankSigner(0), name: customer.fullName, identityNumber: customer.identityNumber, email: customer.email, phone: customer.phone }]); open("create"); }

  return <div className="container-site">
    <header className="relative overflow-hidden rounded-[var(--radius-xl)] border border-electric/15 bg-[linear-gradient(135deg,rgba(14,165,233,.14),rgba(15,23,42,.82)_52%,rgba(139,92,246,.09))] p-5 shadow-2xl sm:p-7">
      <div className="relative flex flex-wrap items-start justify-between gap-5"><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full border border-green-300/20 bg-green-300/10 px-3 py-1 text-xs font-bold text-green-100">● מערכת פעילה</span><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-silver">אזור ניהול מאובטח</span></div><h1 className="text-3xl font-black text-white sm:text-4xl">מרכז ניהול חוזים</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-silver-muted">יצירה, חתימה, מעקב וניהול לקוחות במקום אחד.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => open("create")} className="btn btn-primary text-sm">+ מסמך חדש</button><form action={logoutAction}><button className="btn btn-secondary text-sm">יציאה</button></form></div></div>
      <div className="relative mt-6 grid grid-cols-2 gap-3 xl:grid-cols-5"><StatButton label="מסמכים פעילים" value={stats.active} tone="sky" onClick={() => open("documents", "active")} /><StatButton label="ממתינים לחתימה" value={stats.waiting} tone="amber" onClick={() => open("documents", "waiting")} /><StatButton label="הושלמו" value={stats.completed} tone="green" onClick={() => open("documents", "completed")} /><StatButton label="חותמים מנוהלים" value={stats.signers} tone="violet" onClick={() => open("documents", "all")} /><StatButton label="לקוחות שמורים" value={customers.length} tone="sky" onClick={() => open("customers")} /></div>
    </header>
    {(query.created || query.pdfCreated || query.duplicated) ? <div className="mt-4 rounded-2xl border border-green-400/25 bg-green-400/10 p-4 text-green-100" role="status">הפעולה הושלמה. המסמך זמין בספרייה והלקוחות נשמרו למילוי חוזר.</div> : null}
    {query.sent ? <div className="mt-4 rounded-2xl border border-green-400/25 bg-green-400/10 p-4 text-green-100" role="status">המסמך נשלח בהצלחה.</div> : null}
    {query.mailError ? <div className="mt-4 rounded-2xl border border-red-400/25 bg-red-400/10 p-4 text-red-100" role="alert">לא ניתן לשלוח את המייל כרגע.</div> : null}
    <nav className="sticky top-20 z-40 mt-4 flex gap-1 overflow-x-auto rounded-2xl border border-white/10 bg-[#07111f]/95 p-2 shadow-xl backdrop-blur-xl" aria-label="ניווט באזור הניהול">{tabs.map(([tab, label]) => <button key={tab} type="button" onClick={() => open(tab)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-bold transition ${activeTab === tab ? "bg-electric text-slate-950" : "text-silver hover:bg-white/5 hover:text-white"}`} aria-current={activeTab === tab ? "page" : undefined}>{label}</button>)}<Link href="/work-agreement" className="mr-auto whitespace-nowrap rounded-xl px-4 py-2.5 text-sm text-electric-bright hover:bg-electric/10">מסמכים ציבוריים</Link></nav>
    <div className="mt-6">
      {activeTab === "overview" ? <Overview stats={stats} open={open} /> : null}
      {activeTab === "create" ? <section aria-labelledby="create-title"><SectionTitle kicker="מסמך חדש" title="יצירת מסמך והצבת חתימות" id="create-title" /><form action={createDocumentAction} className="glass space-y-5 rounded-[var(--radius-xl)] p-4 sm:p-7">
        {query.error ? <p className="rounded-xl bg-red-400/10 p-3 text-sm text-red-200">{query.error === "open-fields" ? "נמצאו במסמך פרטים שלא מולאו." : query.error === "signature-fields" ? "יש לסמן במסמך מקום חתימה לכל חותם." : query.error === "signers" ? "יש להשלים שם מלא ותעודת זהות לכל חותם." : "יש להשלים את כל פרטי החובה."}</p> : null}
        <section className="rounded-2xl border border-electric/15 bg-electric/[0.045] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold text-white">הלקוחות והחותמים</h3><p className="mt-1 text-xs text-silver-muted">בחרו לקוח שמור או מלאו פרטים חדשים. כל חותם יקבל קישור אישי.</p></div><button type="button" disabled={signers.length >= 6} onClick={() => setSigners((current) => [...current, blankSigner(current.length)])} className="rounded-full border border-electric/30 px-4 py-2 text-sm font-bold text-electric-bright disabled:opacity-40">+ הוספת חותם</button></div>
          <div className="mt-4 grid gap-4 lg:grid-cols-2">{signers.map((signer, index) => <fieldset key={signer.id} className="rounded-2xl border border-white/10 bg-black/10 p-4"><legend className="px-2 text-sm font-bold text-electric-bright">{signer.label}</legend>{signers.length > 1 ? <button type="button" onClick={() => setSigners((current) => current.filter((_, signerIndex) => signerIndex !== index))} className="float-left text-xs text-red-200">הסרה</button> : null}<label className="block text-xs font-semibold text-silver">מילוי מלקוחות שמורים<select defaultValue="" onChange={(event) => selectCustomer(index, event.target.value)} className="mt-1.5 w-full rounded-xl border border-white/15 bg-[#091627] px-3 py-2.5 text-white"><option value="">בחירת לקוח…</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.fullName} · {customer.identityNumber}</option>)}</select></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><ControlledField label="שם מלא" value={signer.name} onChange={(value) => updateSigner(index, { name: value })} required /><ControlledField label="תעודת זהות" value={signer.identityNumber} onChange={(value) => updateSigner(index, { identityNumber: value.replace(/\D/g, "").slice(0, 9) })} required inputMode="numeric" pattern="[0-9]{9}" /><ControlledField label="אימייל" value={signer.email} onChange={(value) => updateSigner(index, { email: value })} type="email" /><ControlledField label="טלפון" value={signer.phone} onChange={(value) => updateSigner(index, { phone: value })} type="tel" /></div></fieldset>)}</div>
        </section><input type="hidden" name="htmlSigners" value={JSON.stringify(signers)} /><RichDocumentEditor signers={signers} /><div className="sticky bottom-3 z-30 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-electric/20 bg-[#07111f]/95 p-3 shadow-2xl backdrop-blur-xl"><span className="text-xs text-silver-muted">לאחר השמירה יוצגו בספרייה קישור נפרד לכל חותם.</span><button className="btn btn-primary min-w-64" type="submit">שמירה ויצירת קישורי חתימה</button></div>
      </form></section> : null}
      {activeTab === "pdf" ? <section aria-labelledby="pdf-title"><SectionTitle kicker="מסמך קיים" title="העלאת PDF והוספת חתימות" id="pdf-title" /><div className="glass rounded-[var(--radius-xl)] p-4 sm:p-7">{query.pdfError ? <p className="mb-5 rounded-xl bg-red-400/10 p-4 text-sm text-red-200">לא הצלחנו להכין את ה־PDF. בדקו את הקובץ, פרטי החותמים ומיקומי החתימות.</p> : null}<form action={createPdfDocumentAction}><MultiSignaturePdfBuilder /></form></div></section> : null}
      {activeTab === "documents" ? <DocumentLibrary key={libraryFilter} documents={documents} siteUrl={siteUrl} requestedFilter={libraryFilter} /> : null}
      {activeTab === "customers" ? <CustomerLibrary customers={customers} onCreateDocument={createForCustomer} /> : null}
      {activeTab === "security" ? <SecurityPanel twoFactorEnabled={twoFactorEnabled} recoveryCodesRemaining={recoveryCodesRemaining} securityActivity={securityActivity} /> : null}
    </div>
  </div>;
}

function CustomerLibrary({ customers, onCreateDocument }: { customers: Customer[]; onCreateDocument: (customer: Customer) => void }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => { const search = query.trim().toLocaleLowerCase("he"); return customers.filter((customer) => `${customer.fullName} ${customer.identityNumber} ${customer.email} ${customer.phone}`.toLocaleLowerCase("he").includes(search)); }, [customers, query]);
  return <section className="glass rounded-[var(--radius-xl)] p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-electric-bright">מילוי חוזר מהיר</p><h2 className="mt-1 text-2xl font-bold text-white sm:text-3xl">תיקיית לקוחות</h2><p className="mt-2 text-sm text-silver-muted">לקוחות נשמרים אוטומטית בעת יצירת מסמך או PDF.</p></div><span className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm font-bold text-silver">{customers.length} לקוחות</span></div><label className="mt-6 block"><span className="sr-only">חיפוש לקוח</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="חיפוש לפי שם, תעודת זהות, אימייל או טלפון…" className="w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-white placeholder:text-silver-muted" /></label><div className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.length ? filtered.map((customer) => <article key={customer.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{customer.fullName}</h3><p className="mt-1 text-sm text-silver-muted">ת״ז {customer.identityNumber}</p></div><button type="button" onClick={() => onCreateDocument(customer)} className="rounded-full border border-electric/30 bg-electric/10 px-4 py-2 text-xs font-bold text-electric-bright">מסמך חדש</button></div><div className="mt-4 space-y-1 border-t border-white/8 pt-3 text-sm text-silver-muted">{customer.email ? <p>{customer.email}</p> : null}{customer.phone ? <p>{customer.phone}</p> : null}</div></article>) : <p className="rounded-2xl border border-dashed border-white/15 p-10 text-center text-silver-muted lg:col-span-2">לא נמצאו לקוחות מתאימים.</p>}</div></section>;
}

function SecurityPanel({ twoFactorEnabled, recoveryCodesRemaining, securityActivity }: { twoFactorEnabled: boolean; recoveryCodesRemaining: number; securityActivity: SecurityActivity[] }) { return <section aria-labelledby="security-title"><SectionTitle kicker="גישה מוגנת" title="אבטחת החשבון" id="security-title" /><TwoFactorSettings initialEnabled={twoFactorEnabled} initialRecoveryCodesRemaining={recoveryCodesRemaining} /><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-sky-300/15 bg-sky-300/[0.05] p-5"><h3 className="font-bold text-white">הכניסה מנוהלת באמצעות Google</h3><p className="mt-2 text-sm leading-relaxed text-silver-muted">שינוי הסיסמה מתבצע בחשבון Google, והאימות הדו־שלבי כאן מוסיף שכבת הגנה נוספת.</p><a href="https://myaccount.google.com/security" target="_blank" rel="noreferrer" className="btn btn-secondary mt-4 text-sm">פתיחת אבטחת חשבון Google</a></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h3 className="font-bold text-white">פעילות כניסה אחרונה</h3><div className="mt-3 space-y-2">{securityActivity.length ? securityActivity.map((item) => <div key={item.id} className="rounded-xl border border-white/8 bg-black/10 p-3"><p className="text-sm font-bold text-silver">כניסה מאושרת · {new Intl.DateTimeFormat("he-IL", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.createdAt))}</p><p className="mt-1 truncate text-xs text-silver-muted" title={item.device}>{item.device}</p><p className="mt-1 text-[11px] text-silver-muted">מזהה רשת: {item.ipHint}</p></div>) : <p className="text-sm text-silver-muted">פעילות חדשה תופיע כאן לאחר הכניסה הבאה.</p>}</div></div></div></section>; }
function Overview({ stats, open }: { stats: { waiting: number; completed: number }; open: (tab: Tab, filter?: LibraryFilter) => void }) { return <section className="grid gap-4 lg:grid-cols-4"><QuickAction title="יצירת מסמך" text="בחירת לקוח, הוספת חותמים וסימון מקום לכל חתימה." action="התחלת מסמך" onClick={() => open("create")} /><QuickAction title="חתימה על PDF" text="העלאת PDF, הוספת חותמים וסימון מקומות חתימה." action="העלאת PDF" onClick={() => open("pdf")} /><QuickAction title="תיקיית לקוחות" text="בחירת לקוח שמור ומילוי מהיר במסמך חדש." action="פתיחת הלקוחות" onClick={() => open("customers")} /><QuickAction title="מעקב מסמכים" text={`${stats.waiting} ממתינים ו־${stats.completed} הושלמו.`} action="פתיחת הספרייה" onClick={() => open("documents")} /></section>; }
function QuickAction({ title, text, action, onClick }: { title: string; text: string; action: string; onClick: () => void }) { return <article className="glass rounded-2xl p-6"><h2 className="text-xl font-bold text-white">{title}</h2><p className="mt-2 min-h-12 text-sm leading-relaxed text-silver-muted">{text}</p><button type="button" onClick={onClick} className="btn btn-secondary mt-5 w-full text-sm">{action}</button></article>; }
function LoadingPanel({ label }: { label: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-10 text-center text-sm text-silver-muted" role="status">{label}</div>; }
function SectionTitle({ kicker, title, id }: { kicker: string; title: string; id: string }) { return <div className="mb-5"><p className="text-sm font-bold text-electric-bright">{kicker}</p><h2 id={id} className="mt-1 text-2xl font-bold text-white sm:text-3xl">{title}</h2></div>; }
function ControlledField({ label, value, onChange, required, type = "text", inputMode, pattern }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string; inputMode?: "numeric"; pattern?: string }) { return <label className="block text-xs font-semibold text-silver">{label}<input value={value} onChange={(event) => onChange(event.target.value)} required={required} type={type} inputMode={inputMode} pattern={pattern} maxLength={pattern ? 9 : undefined} className="mt-1.5 w-full rounded-xl border border-white/15 bg-[#091627] px-3 py-2.5 text-white" /></label>; }
function StatButton({ label, value, tone, onClick }: { label: string; value: number; tone: "sky" | "amber" | "green" | "violet"; onClick: () => void }) { const colors = { sky: "border-sky-300/15 bg-sky-300/[0.07] text-sky-100", amber: "border-amber-300/15 bg-amber-300/[0.07] text-amber-100", green: "border-green-300/15 bg-green-300/[0.07] text-green-100", violet: "border-violet-300/15 bg-violet-300/[0.07] text-violet-100" }; return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-right transition hover:-translate-y-0.5 hover:border-electric/30 ${colors[tone]}`}><span className="block text-2xl font-black sm:text-3xl">{value.toLocaleString("he-IL")}</span><span className="mt-1 block text-xs font-bold opacity-75">{label}</span></button>; }
